"""P9.2 02b Step 1 regression — AMF positional-anchoring fixtures.

Pins the per-case offer-price extraction across the 14 false-positive
cases catalogued in the Step 0 audit (`docs/phase-09/p92_02b_step0_audit.md`)
plus the 3 false-alarm cases the pre-review heuristic flagged but the
legacy parser actually got right.

Two contracts:

1. **FP fixtures (14)** — `_extract_first_price` (the current parser
   helper) is expected to return the **corrected** price after the
   Step 1 fix ships. **Pre-fix, these tests fail by design** — the
   commit "test(p92-02b): regression fixtures (failing red)" lands them
   red, and each subsequent pattern fix turns a subset green.

2. **False-alarm fixtures (3)** — already green pre-fix. The fix must
   keep them green (multi-bullet + `dorénavant` formulations must remain
   correctly matched).

Excerpts live in ``tests/fixtures/p92_02b/<ref>_excerpt.txt`` and were
generated by ``scripts/p92_02b_extract_fixtures.py``.
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import pytest

from src.ingestion.amf.parser import _extract_first_price

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "p92_02b"


def _read_excerpt(ref: str) -> str:
    return (FIXTURES_DIR / f"{ref}_excerpt.txt").read_text(encoding="utf-8")


# (ref, target, expected_price_after_fix, pattern_label)
FP_CASES = [
    ("224C0915", "TRAVEL TECHNOLOGY INTERACTIVE", Decimal("2.85"), "BLOCK_PURCHASE"),
    ("224C1289", "TRAVEL TECHNOLOGY INTERACTIVE", Decimal("2.85"), "BLOCK_PURCHASE"),
    ("218C1907", "SERMA GROUP", Decimal("235"), "BLOCK_PURCHASE"),
    ("218C2028", "SERMA GROUP", Decimal("235"), "BLOCK_PURCHASE"),
    ("221C1910", "GENKYOTEX", Decimal("2.85"), "DIVIDEND_TRAP"),
    ("218C1043", "CFI", Decimal("1.00"), "SURENCHERE"),
    ("220C4135", "LE BELIER", Decimal("38.18"), "DIVIDEND_TRAP"),
    ("224C1700", "GALIMMO", Decimal("14.83"), "BLOCK_PURCHASE"),
    ("224C2193", "NHOA", Decimal("1.25"), "SURENCHERE"),
    ("224C1145", "OSMOZIS", Decimal("15"), "DIVIDEND_TRAP"),
    ("223C2035", "TECHNICOLOR CREATIVE STUDIOS", Decimal("1.63"), "OCEANE_BSA"),
    ("226C0661", "MEDIA 6", Decimal("9.89"), "SURENCHERE"),
    ("226C0645", "MEDIA 6", Decimal("9.89"), "SURENCHERE"),
    ("225C1227", "GROUPE ETPO", Decimal("82.33"), "DIVIDEND_TRAP"),
]

FALSE_ALARM_CASES = [
    ("226C0550", "TERACT", Decimal("3.12"), "MULTI_BULLET"),
    ("226C0157", "TERACT", Decimal("3.12"), "MULTI_BULLET"),
    ("224C1861", "NHOA", Decimal("1.25"), "DORENAVANT_PHRASING"),
]


@pytest.mark.parametrize(
    ("ref", "target", "expected", "pattern"),
    FP_CASES,
    ids=[f"{ref}_{pattern}" for ref, _, _, pattern in FP_CASES],
)
def test_fp_case_corrected_after_fix(
    ref: str, target: str, expected: Decimal, pattern: str
) -> None:
    """Parser must extract the corrected price on each Step 0 false positive."""
    text = _read_excerpt(ref)
    price, _ = _extract_first_price(text)
    assert price == expected, (
        f"{target} ({ref}, {pattern}): expected {expected} €, got {price} €. "
        f"Step 1 fix incomplete for this pattern."
    )


@pytest.mark.parametrize(
    ("ref", "target", "expected", "pattern"),
    FALSE_ALARM_CASES,
    ids=[f"{ref}_{pattern}" for ref, _, _, pattern in FALSE_ALARM_CASES],
)
def test_false_alarm_unchanged(ref: str, target: str, expected: Decimal, pattern: str) -> None:
    """Parser must preserve the already-correct extraction on multi-bullet
    and `dorénavant` phrasings — these were already right pre-fix."""
    text = _read_excerpt(ref)
    price, _ = _extract_first_price(text)
    assert price == expected, (
        f"{target} ({ref}, {pattern}): regression — pre-fix value was {expected} €, "
        f"got {price} €. The Step 1 fix introduced a regression here."
    )
